name: lashae_s_application
description: SmartVoiceNotes
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  flutter_svg: ^2.0.12
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  connectivity_plus: ^7.0.0
  supabase_flutter: ^2.10.1
  dio: ^5.9.0
  share_plus: ^12.0.1
  file_picker: ^10.3.3
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_sound: ^9.2.13
  permission_handler: ^12.0.1
  http: ^1.5.0
  uuid: ^4.5.1
  web: any
  sizer: ^3.1.3
  google_fonts: ^6.3.1
  pdf: ^3.11.1
  record: ^6.1.0
  lottie: ^3.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/images/
    - assets/animations/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterMedium.ttf
          weight: 400
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSansRegular.ttf
          weight: 400
        - asset: assets/fonts/OpenSansSemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSansBold.ttf
          weight: 700
    - family: Quattrocento
      fonts:
        - asset: assets/fonts/Quattrocento/Quattrocento-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quattrocento/Quattrocento-Bold.ttf
          weight: 700
